
# Create a non-existent target that gets built every time
.PHONY: ALWAYS_MAKE

# Generate C source for git version
$(BUILDDIR)/version.c.newest: ALWAYS_MAKE
	@echo '// Contains Git version string (automatically generated by build).' > $@
	@echo '//' >> $@
	@echo '// (C) Copyright 2014-$(shell date +'%Y') Xo Wang <xo@geekshavefeelings.com>' >> $@
	@echo '// SPDX-License-Identifier: Apache-2.0' >> $@
	@echo '' >> $@
	@echo 'const char * const g_build_version = "$(GIT_VERSION)";' >> $@
	@echo 'Building $(PROJECT) $(GIT_VERSION)'
	
# If the generated C has changed from the current, copy it over
$(VERSIONSRC): $(BUILDDIR)/version.c.newest
	@cmp -s $< $@ || cp $< $@
